module.exports = () => {
  return [
    {
      uuid: 'a56c199f-be27-4be9-acf5-aeb924eafcc1',
      category: 'question',
      subject: 'Can an algorithm distinguish living organisms from non-living things?',
      details: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
      tags: '["Hot Topic", "Recent", "test tag question"]',
      author: '[{"id": "48e40a9c-c5e9-4d63-9aba-b77cdf4ca67b","name": "Developer Test"}, {"name": "Lui Test"}]',
      userId: '48e40a9c-c5e9-4d63-9aba-b77cdf4ca67b',
      version: '1.0',
      hypothesisStatus: '',
      status: 'publish'
    },
    {
      uuid: 'd3a1cf70-69ef-472e-8a89-bfbf478b8c3b',
      category: 'hypothesis',
      subject: 'Non-living systems are characterized by more broadly distributed changes in speed and/or direction.',
      details: 'More specifically, living systems are not only chaotic, but also nondeterminate dynamical systems. We expect that these are essential properties that are distributed over behaviors in a scale-free manner, similar to the Lévy search patterns found in many biological systems.',
      tags: '["test tag hypothesis"]',
      author: '[]',
      userId: '48e40a9c-c5e9-4d63-9aba-b77cdf4ca67b',
      version: '1.0',
      hypothesisStatus: '',
      status: 'publish'
    },
    {
      uuid: 'd2933c5a-97e7-42f6-9dfc-8c325437dbf2',
      category: 'experiment',
      subject: 'Fake Life Recognition Contest',
      details: 'A list of unlabeled datasets are made available online. Some are time series of real living systems, and some are generated by non-living systems. Participants can test their algorithms on these public datasets, but their algorithms will be judged based on unreleased datasets. The algorithms might, or might not, be able to distinguish the living systems from the non-living ones.',
      tags: '["test tag experiment"]',
      author: '[]',
      userId: '48e40a9c-c5e9-4d63-9aba-b77cdf4ca67b',
      version: '1.0',
      hypothesisStatus: '',
      status: 'publish'
    },
    {
      uuid: '49c14584-4f31-4683-8bad-5bdedb30512f',
      category: 'data',
      subject: 'Ikegami Lab\'s prediction data',
      details: 'The datasets consist in time series of trajectory positions in 2D (those are meant as actual spatial trajectories), which correspond to either artificial or real living systems. Each dataset comes in the form of a 20Mb or so CSV file with 3 columns labelled "t", "x" and "y", with 10,000 rows. https://github.com/LanaSina/FLR_contest',
      tags: '["test tag data"]',
      author: '[]',
      userId: '48e40a9c-c5e9-4d63-9aba-b77cdf4ca67b',
      version: '1.0',
      hypothesisStatus: '',
      status: 'publish'
    },
    {
      uuid: '92a41cad-606c-4e5f-bef8-3a42952fc09e',
      category: 'analysis',
      subject: 'Algorithm made correct classifications',
      details: 'The algorithm made correct classifications on 7 our of 10 of the training datasets, and 3 out of 4 of the test datasets. These results support the hypothesis.',
      tags: '["test tag analysis"]',
      author: '[]',
      userId: '48e40a9c-c5e9-4d63-9aba-b77cdf4ca67b',
      version: '1.0',
      hypothesisStatus: 'supports',
      status: 'publish'
    },
    {
      uuid: '2c5982cb-a63d-47c4-8778-540410551fff',
      category: 'analysis',
      subject: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      tags: '["test tag analysis"]',
      author: '[]',
      userId: '48e40a9c-c5e9-4d63-9aba-b77cdf4ca67b',
      version: '1.0',
      hypothesisStatus: 'refutes',
      status: 'publish'
    },
    {
      uuid: '376d8977-5edd-4c23-a1f0-63dc6beea457',
      category: 'question',
      subject: 'Can an algorithm distinguish living organisms from non-living things?',
      details: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
      tags: '["Hot Topic", "Recent", "test tag question"]',
      author: '[]',
      userId: '48e40a9c-c5e9-4d63-9aba-b77cdf4ca67b',
      version: '1.0',
      hypothesisStatus: '',
      status: 'publish'
    },
    {
      uuid: 'd3a1cf70-69ef-472e-8a89-bfbf478b8c3c',
      category: 'hypothesis',
      subject: 'This is a different hypothesis',
      details: 'This hypothesis has a description',
      tags: '[]',
      author: '[]',
      userId: '48e40a9c-c5e9-4d63-9aba-b77cdf4ca67b',
      version: '1.0',
      hypothesisStatus: '',
      status: 'publish'
    }
  ]
}
